In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

from urllib.request import urlopen
from bs4 import BeautifulSoup as bs

In [2]:
url = r'https://www.hubertiming.com/results/2018mlk'
html = urlopen(url)

In [3]:
soup = bs(html)

In [4]:
print(soup.title.text)

Race results for the 2018 MLK Dream Run!

In [5]:
links = soup.find_all('a', href=True)
for link in links :
    print(link['href'])

https://www.mlkdreamrun.com/
mailto:timing@hubertiming.com
https://www.hubertiming.com
/results/2018MLK10K
/results/2018MLK15K
/results/summary/2018MLK
#tabs-1
https://www.hubertiming.com/
https://facebook.com/hubertiming/

In [7]:

data = []
all_rows = soup.find_all('tr')
first_row = all_rows[5].find_all('td')

l = []
for tag in first_row :
    for x in tag :
        l.append(x.strip())

l

['1',
 '1191',
 'MAX RANDOLPH',
 'M',
 '29',
 'WASHINGTON',
 '16:48',
 '5:25',
 '1 of 78',
 'M 21-39',
 '1 of 33',
 '0:08',
 '16:56']

In [8]:
soup.find_all('th')

[<th>Place</th>,
 <th>Bib</th>,
 <th>Name</th>,
 <th>Gender</th>,
 <th>Age</th>,
 <th>City</th>,
 <th>Chip Time</th>,
 <th>Chip Pace</th>,
 <th>Gender Place</th>,
 <th>Age Group</th>,
 <th>Age Group Place</th>,
 <th>Time to Start</th>,
 <th>Gun Time</th>]

In [9]:
headers = []
for x in soup.find_all('th') :
    headers.append(x.text)

In [10]:
data = []
for c in range(len(all_rows)) :
    if c < 5 : continue
    row = all_rows[c].find_all('td')
    l = []
    for tag in row :
        for x in tag :
            l.append(x.strip())
    data.append(l)
    
data

[['1',
  '1191',
  'MAX RANDOLPH',
  'M',
  '29',
  'WASHINGTON',
  '16:48',
  '5:25',
  '1 of 78',
  'M 21-39',
  '1 of 33',
  '0:08',
  '16:56'],
 ['2',
  '1080',
  'NEED NAME KAISER RUNNER',
  'M',
  '25',
  'PORTLAND',
  '17:31',
  '5:39',
  '2 of 78',
  'M 21-39',
  '2 of 33',
  '0:09',
  '17:40'],
 ['3',
  '1275',
  'DAN FRANEK',
  'M',
  '52',
  'PORTLAND',
  '18:15',
  '5:53',
  '3 of 78',
  'M 40-54',
  '1 of 27',
  '0:07',
  '18:22'],
 ['4',
  '1223',
  'PAUL TAYLOR',
  'M',
  '54',
  'PORTLAND',
  '18:31',
  '5:58',
  '4 of 78',
  'M 40-54',
  '2 of 27',
  '0:07',
  '18:38'],
 ['5',
  '1245',
  'THEO KINMAN',
  'M',
  '22',
  '19:31',
  '6:17',
  '5 of 78',
  'M 21-39',
  '3 of 33',
  '0:09',
  '19:40'],
 ['6',
  '1185',
  'MELISSA GIRGIS',
  'F',
  '27',
  'PORTLAND',
  '19:39',
  '6:20',
  '1 of 113',
  'F 21-39',
  '1 of 53',
  '0:07',
  '19:46'],
 ['7',
  '1251',
  'CHARLIE COGGESHALL',
  'M',
  '39',
  'PORTLAND',
  '19:51',
  '6:24',
  '6 of 78',
  'M 21-39',
  '4 of 33',
  '0:10',
  '20:01'],
 ['8',
  '1154',
  'UNKNOWN RUNNER SEE TIMER',
  'M',
  '24:58',
  '8:03',
  '7 of 78',
  '1 of 9',
  '2:00',
  '26:58'],
 ['9',
  '1163',
  'UNKNOWN RUNNER SEE TIMER',
  'M',
  '25:01',
  '8:04',
  '8 of 78',
  '2 of 9',
  '1:59',
  '27:00'],
 ['10',
  '1242',
  'KIMONTI WILSON',
  'F',
  '48',
  '25:01',
  '8:04',
  '2 of 113',
  'F 40-54',
  '1 of 37',
  '1:59',
  '27:00'],
 ['11',
  '1017',
  'COREY MCMANUS',
  'M',
  '37',
  'BEAVERTON',
  '25:17',
  '8:09',
  '9 of 78',
  'M 21-39',
  '5 of 33',
  '0:22',
  '25:39'],
 ['12',
  '1112',
  'MITCHELL JOHNSON',
  'M',
  '25',
  'PORTLAND',
  '25:31',
  '8:13',
  '10 of 78',
  'M 21-39',
  '6 of 33',
  '0:15',
  '25:46'],
 ['13',
  '1062',
  'ALEX KABA',
  'M',
  '36',
  'PORTLAND',
  '25:31',
  '8:14',
  '11 of 78',
  'M 21-39',
  '7 of 33',
  '0:14',
  '25:45'],
 ['14',
  '1227',
  'ROBYN MCGILLIS',
  'F',
  '44',
  'PORTLAND',
  '25:44',
  '8:18',
  '3 of 113',
  'F 40-54',
  '2 of 37',
  '0:08',
  '25:52'],
 ['15',
  '1067',
  'MITCHELL WARDEN',
  'M',
  '29',
  'PORTLAND',
  '25:46',
  '8:19',
  '12 of 78',
  'M 21-39',
  '8 of 33',
  '0:14',
  '26:00'],
 ['16',
  '1136',
  'JULIA METZ',
  'F',
  '32',
  'PORTLAND',
  '26:31',
  '8:33',
  '4 of 113',
  'F 21-39',
  '2 of 53',
  '0:33',
  '27:04'],
 ['17',
  '1199',
  'JEREMY AREZZINI',
  'M',
  '38',
  'LAKE OSWEGO',
  '26:44',
  '8:37',
  '13 of 78',
  'M 21-39',
  '9 of 33',
  '0:41',
  '27:25'],
 ['18',
  '1252',
  'ETHAN POWELL',
  'M',
  '26:52',
  '8:40',
  '14 of 78',
  '3 of 9',
  '0:11',
  '27:03'],
 ['19',
  '1231',
  'TIMOTHY KEARNEY',
  'M',
  '42',
  'PORTLAND',
  '26:58',
  '8:42',
  '15 of 78',
  'M 40-54',
  '3 of 27',
  '0:11',
  '27:09'],
 ['20',
  '1108',
  'TIMOTHY RINGERING',
  'M',
  '50',
  'VANCOUVER',
  '27:02',
  '8:43',
  '16 of 78',
  'M 40-54',
  '4 of 27',
  '0:10',
  '27:12'],
 ['21',
  '1118',
  'PONTUS JADERHOLM',
  'M',
  '43',
  'PORTLAND',
  '27:08',
  '8:45',
  '17 of 78',
  'M 40-54',
  '5 of 27',
  '0:13',
  '27:21'],
 ['22',
  '1246',
  'KERRY FLAGG',
  'M',
  '27:10',
  '8:45',
  '18 of 78',
  '4 of 9',
  '0:10',
  '27:20'],
 ['23',
  '1244',
  'JARRED FLAGG',
  'M',
  '27:11',
  '8:46',
  '19 of 78',
  '5 of 9',
  '0:10',
  '27:21'],
 ['24',
  '1224',
  'KEN SKEEN',
  'M',
  '57',
  'PORTLAND',
  '27:12',
  '8:46',
  '20 of 78',
  'M 55+',
  '1 of 5',
  '0:18',
  '27:30'],
 ['25',
  '1065',
  'SARA KOPTON',
  'F',
  '40',
  'PORTLAND',
  '27:27',
  '8:51',
  '5 of 113',
  'F 40-54',
  '3 of 37',
  '0:20',
  '27:47'],
 ['26',
  '1274',
  'KAISER GUEST',
  'F',
  '40',
  'PORTLAND',
  '27:37',
  '8:54',
  '6 of 113',
  'F 40-54',
  '4 of 37',
  '0:09',
  '27:46'],
 ['27',
  '1208',
  'JUSTIN PERZ',
  'M',
  '33',
  'PORTLAND',
  '27:39',
  '8:55',
  '21 of 78',
  'M 21-39',
  '10 of 33',
  '0:38',
  '28:17'],
 ['28',
  '1072',
  'ESTELA SÁNCHEZ',
  'F',
  '41',
  'PORTLAND',
  '27:45',
  '8:57',
  '7 of 113',
  'F 40-54',
  '5 of 37',
  '0:08',
  '27:53'],
 ['29',
  '1018',
  'JASON WILLIAMS',
  'M',
  '41',
  'PORTLAND',
  '27:50',
  '8:58',
  '22 of 78',
  'M 40-54',
  '6 of 27',
  '0:23',
  '28:13'],
 ['30',
  '1297',
  'ADRIANA BRITTON',
  'F',
  '53',
  'PORTLAND',
  '27:54',
  '9:00',
  '8 of 113',
  'F 40-54',
  '6 of 37',
  '0:12',
  '28:06'],
 ['31',
  '1117',
  'MARK WOOD',
  'M',
  '43',
  'PORTLAND',
  '28:05',
  '9:03',
  '23 of 78',
  'M 40-54',
  '7 of 27',
  '0:30',
  '28:35'],
 ['32',
  '1201',
  'STEVE CRANDELL',
  'M',
  '61',
  'PORTLAND',
  '28:06',
  '9:03',
  '24 of 78',
  'M 55+',
  '2 of 5',
  '0:09',
  '28:15'],
 ['33',
  '1110',
  'DARRELL KRIECHBAUM',
  'M',
  '53',
  'PORTLAND',
  '28:11',
  '9:05',
  '25 of 78',
  'M 40-54',
  '8 of 27',
  '0:12',
  '28:23'],
 ['34',
  '1104',
  'JANICE JACOBS',
  'F',
  '55',
  'SALEM',
  '28:11',
  '9:05',
  '9 of 113',
  'F 55+',
  '1 of 14',
  '0:15',
  '28:26'],
 ['35',
  '1300',
  'CORY ANDERSON',
  'M',
  '30',
  'PORTLAND',
  '28:14',
  '9:06',
  '26 of 78',
  'M 21-39',
  '11 of 33',
  '0:19',
  '28:33'],
 ['36',
  '1238',
  'PAUL SUMMERS',
  'M',
  '24',
  'PORTLAND',
  '28:21',
  '9:08',
  '27 of 78',
  'M 21-39',
  '12 of 33',
  '0:15',
  '28:36'],
 ['37',
  '1298',
  'ALEX NGUYEN',
  'M',
  '26',
  '28:22',
  '9:09',
  '28 of 78',
  'M 21-39',
  '13 of 33',
  '0:19',
  '28:41'],
 ['38',
  '1157',
  'JEREMY SWEET',
  'M',
  '27',
  'PORTLAND',
  '28:32',
  '9:12',
  '29 of 78',
  'M 21-39',
  '14 of 33',
  '0:20',
  '28:52'],
 ['39',
  '1106',
  'DANIEL JOHNSTON',
  'M',
  '43',
  'PORTLAND',
  '28:32',
  '9:12',
  '30 of 78',
  'M 40-54',
  '9 of 27',
  '0:12',
  '28:44'],
 ['40',
  '1196',
  'LIZANN DUNEGAN',
  'F',
  '53',
  'PORTLAND',
  '28:34',
  '9:13',
  '10 of 113',
  'F 40-54',
  '7 of 37',
  '0:14',
  '28:48'],
 ['41',
  '1239',
  'ALYX WYNN',
  'F',
  '28',
  'PORTLAND',
  '28:37',
  '9:14',
  '11 of 113',
  'F 21-39',
  '3 of 53',
  '0:21',
  '28:58'],
 ['42',
  '1087',
  'YALOUNDA HUNT',
  'F',
  '60',
  'PORTLAND',
  '28:40',
  '9:14',
  '12 of 113',
  'F 55+',
  '2 of 14',
  '0:09',
  '28:49'],
 ['43',
  '1068',
  'SERGIO RIVERA',
  'M',
  '32',
  'PORTLAND',
  '28:41',
  '9:15',
  '31 of 78',
  'M 21-39',
  '15 of 33',
  '0:21',
  '29:02'],
 ['44',
  '1071',
  'PEDRO FLORES',
  'M',
  '42',
  'PORTLAND',
  '28:42',
  '9:15',
  '32 of 78',
  'M 40-54',
  '10 of 27',
  '0:08',
  '28:50'],
 ['45',
  '1159',
  'JEFF DOWNEY',
  'M',
  '36',
  'PORTLAND',
  '28:42',
  '9:15',
  '33 of 78',
  'M 21-39',
  '16 of 33',
  '0:19',
  '29:01'],
 ['46',
  '1241',
  'NICK SCHUDER',
  'M',
  '44',
  'PORTLAND',
  '28:45',
  '9:16',
  '34 of 78',
  'M 40-54',
  '11 of 27',
  '0:18',
  '29:03'],
 ['47',
  '1023',
  'JOHN GARDNER',
  'M',
  '44',
  'PORTLAND',
  '28:51',
  '9:18',
  '35 of 78',
  'M 40-54',
  '12 of 27',
  '0:25',
  '29:16'],
 ['48',
  '1253',
  'JAZMIN BEMBRY',
  'F',
  '23',
  'PORTLAND',
  '28:56',
  '9:20',
  '13 of 113',
  'F 21-39',
  '4 of 53',
  '0:15',
  '29:11'],
 ['49',
  '1247',
  'THEO KINWAN',
  'F',
  '29:09',
  '9:24',
  '14 of 113',
  '6 of 9',
  '0:10',
  '29:19'],
 ['50',
  '1019',
  'ERIKA TURNEY',
  'F',
  '46',
  'BATTLE GROUNDB',
  '29:10',
  '9:24',
  '15 of 113',
  'F 40-54',
  '8 of 37',
  '0:24',
  '29:34'],
 ['51',
  '1066',
  'MICHELLE FRAZIER',
  'F',
  '27',
  'PORTLAND',
  '29:12',
  '9:25',
  '16 of 113',
  'F 21-39',
  '5 of 53',
  '0:13',
  '29:25'],
 ['52',
  '1151',
  'CHRISTINA LECHER',
  'F',
  '31',
  'MILWAUKEE',
  '29:21',
  '9:28',
  '17 of 113',
  'F 21-39',
  '6 of 53',
  '0:18',
  '29:39'],
 ['53',
  '1152',
  'BERNARD RAHMING',
  'M',
  '31',
  'PORTLAND',
  '29:21',
  '9:28',
  '36 of 78',
  'M 21-39',
  '17 of 33',
  '0:18',
  '29:39'],
 ['54',
  '1095',
  'TROY PICKARD',
  'M',
  '36',
  'PORTLAND',
  '29:22',
  '9:28',
  '37 of 78',
  'M 21-39',
  '18 of 33',
  '0:44',
  '30:06'],
 ['55',
  '1028',
  'JONATHAN TILLMAN',
  'M',
  '49',
  'PORTLAND',
  '29:23',
  '9:28',
  '38 of 78',
  'M 40-54',
  '13 of 27',
  '0:24',
  '29:47'],
 ['56',
  '1174',
  'CYNJAYSHA BOLES',
  'F',
  '26',
  'PORTLAND',
  '29:46',
  '9:36',
  '18 of 113',
  'F 21-39',
  '7 of 53',
  '0:09',
  '29:55'],
 ['57',
  '1013',
  'TERESA MCGRATH',
  'F',
  '65',
  'PORTLAND',
  '29:51',
  '9:37',
  '19 of 113',
  'F 55+',
  '3 of 14',
  '0:10',
  '30:01'],
 ['58',
  '1237',
  'ERYN HOERSTER',
  'F',
  '37',
  'PORTLAND',
  '30:41',
  '9:53',
  '20 of 113',
  'F 21-39',
  '8 of 53',
  '0:40',
  '31:21'],
 ['59',
  '1230',
  'EDUARDO ARIZAGA',
  'M',
  '38',
  'PORTLAND',
  '30:55',
  '9:58',
  '39 of 78',
  'M 21-39',
  '19 of 33',
  '0:47',
  '31:42'],
 ['60',
  '1236',
  'BEN HOERSTER',
  'M',
  '37',
  'PORTLAND',
  '31:29',
  '10:09',
  '40 of 78',
  'M 21-39',
  '20 of 33',
  '0:43',
  '32:12'],
 ['61',
  '1125',
  'ABIGAIL VAN GELDER',
  'F',
  '36',
  'PORTLAND',
  '31:37',
  '10:12',
  '21 of 113',
  'F 21-39',
  '9 of 53',
  '0:16',
  '31:53'],
 ['62',
  '1053',
  'DAMIANA KING',
  'F',
  '38',
  'PORTLAND',
  '32:02',
  '10:20',
  '22 of 113',
  'F 21-39',
  '10 of 53',
  '0:12',
  '32:14'],
 ['63',
  '1010',
  'HEATHER CERMAK',
  'F',
  '29',
  'PORTLAND',
  '32:11',
  '10:23',
  '23 of 113',
  'F 21-39',
  '11 of 53',
  '0:41',
  '32:52'],
 ['64',
  '1011',
  'COLE CHRIST',
  'M',
  '19',
  'PORTLAND',
  '32:11',
  '10:23',
  '41 of 78',
  'M 20 and Under',
  '1 of 7',
  '0:42',
  '32:53'],
 ['65',
  '1179',
  'MIRIAN HINOJOSA',
  'F',
  '40',
  'MILWAUKIE',
  '32:48',
  '10:34',
  '24 of 113',
  'F 40-54',
  '9 of 37',
  '0:14',
  '33:02'],
 ['66',
  '1183',
  'CAMERON SEIDLING',
  'M',
  '28',
  'PORTLAND',
  '33:16',
  '10:44',
  '42 of 78',
  'M 21-39',
  '21 of 33',
  '0:37',
  '33:53'],
 ['67',
  '1137',
  'LARRY JENKINS',
  'M',
  '31',
  'PORTLAND',
  '33:16',
  '10:44',
  '43 of 78',
  'M 21-39',
  '22 of 33',
  '0:34',
  '33:50'],
 ['68',
  '1173',
  'ALYS MEYER',
  'F',
  '12',
  'PORTLAND',
  '33:33',
  '10:49',
  '25 of 113',
  'F 20 and Under',
  '1 of 6',
  '0:27',
  '34:00'],
 ['69',
  '1103',
  'SARAH MEYER',
  'F',
  '34',
  'PORTLAND',
  '33:36',
  '10:50',
  '26 of 113',
  'F 21-39',
  '12 of 53',
  '0:26',
  '34:02'],
 ['70',
  '1100',
  'ELIZABETH TAYLOR',
  'F',
  '39',
  'PORTLAND',
  '33:40',
  '10:51',
  '27 of 113',
  'F 21-39',
  '13 of 53',
  '0:37',
  '34:17'],
 ['71',
  '1190',
  'RICARDO BARRERA',
  'M',
  '45',
  'PORTLAND',
  '34:00',
  '10:58',
  '44 of 78',
  'M 40-54',
  '14 of 27',
  '0:29',
  '34:29'],
 ['72',
  '1127',
  'MOIRA SHERRY',
  'F',
  '24',
  'PORTLAND',
  '34:14',
  '11:02',
  '28 of 113',
  'F 21-39',
  '14 of 53',
  '0:19',
  '34:33'],
 ['73',
  '1299',
  'BRYNDON COUGHLIN',
  'M',
  '27',
  'PORTLAND',
  '34:16',
  '11:03',
  '45 of 78',
  'M 21-39',
  '23 of 33',
  '0:44',
  '35:00'],
 ['74',
  '1261',
  'CHADI BOTRNS',
  'M',
  '34:19',
  '11:04',
  '46 of 78',
  '7 of 9',
  '0:30',
  '34:49'],
 ['75',
  '1006',
  'HELEN SHARP',
  'F',
  '53',
  'FOREST GROVE',
  '34:32',
  '11:08',
  '29 of 113',
  'F 40-54',
  '10 of 37',
  '0:16',
  '34:48'],
 ['76',
  '1165',
  'CLAYTON BELL',
  'M',
  '40',
  'PORTLAND',
  '34:38',
  '11:10',
  '47 of 78',
  'M 40-54',
  '15 of 27',
  '0:18',
  '34:56'],
 ['77',
  '1219',
  'PATRICIA ENGLE',
  'F',
  '43',
  'PORTLAND',
  '34:42',
  '11:11',
  '30 of 113',
  'F 40-54',
  '11 of 37',
  '0:30',
  '35:12'],
 ['78',
  '1200',
  'BEN KLEVIT',
  'M',
  '53',
  'LAKE OSWEGO',
  '34:49',
  '11:13',
  '48 of 78',
  'M 40-54',
  '16 of 27',
  '0:39',
  '35:28'],
 ['79',
  '1132',
  'KAYLEN GIBBENS',
  'F',
  '41',
  'HILLSBORO',
  '34:54',
  '11:15',
  '31 of 113',
  'F 40-54',
  '12 of 37',
  '0:20',
  '35:14'],
 ['80',
  '1122',
  'AUGUST EPSTEIN',
  'M',
  '26',
  'PORTLAND',
  '35:57',
  '11:36',
  '49 of 78',
  'M 21-39',
  '24 of 33',
  '0:12',
  '36:09'],
 ['81',
  '1121',
  'SAMANTHA PINKERTON',
  'F',
  '26',
  'PORTLAND',
  '35:58',
  '11:36',
  '32 of 113',
  'F 21-39',
  '15 of 53',
  '0:12',
  '36:10'],
 ['82',
  '1107',
  'NICOLE SCHULMERICH',
  'F',
  '33',
  'PORTLAND',
  '36:10',
  '11:40',
  '33 of 113',
  'F 21-39',
  '16 of 53',
  '0:27',
  '36:37'],
 ['83',
  '1056',
  'MARYJANE YACOBY',
  'F',
  '35',
  'VANCOUVER',
  '36:53',
  '11:54',
  '34 of 113',
  'F 21-39',
  '17 of 53',
  '0:22',
  '37:15'],
 ['84',
  '1057',
  'JOEL YACOBY',
  'M',
  '40',
  'VANCOUVER',
  '36:56',
  '11:54',
  '50 of 78',
  'M 40-54',
  '17 of 27',
  '0:22',
  '37:18'],
 ['85',
  '1055',
  'JILL TIMSHEL',
  'F',
  '39',
  'BATTLE GROUND',
  '36:56',
  '11:55',
  '35 of 113',
  'F 21-39',
  '18 of 53',
  '0:23',
  '37:19'],
 ['86',
  '1022',
  'CHRISTIE VANG',
  'F',
  '32',
  'PORTLAND',
  '37:02',
  '11:57',
  '36 of 113',
  'F 21-39',
  '19 of 53',
  '0:29',
  '37:31'],
 ['87',
  '1192',
  'JUNE REYES',
  'F',
  '30',
  'PORTLAND',
  '37:18',
  '12:02',
  '37 of 113',
  'F 21-39',
  '20 of 53',
  '0:20',
  '37:38'],
 ['88',
  '1078',
  'FRED SMITH',
  'M',
  '46',
  'PORTLAND',
  '38:06',
  '12:17',
  '51 of 78',
  'M 40-54',
  '18 of 27',
  '0:18',
  '38:24'],
 ['89',
  '1077',
  'BRIANNA MILLER',
  'F',
  '25',
  'PORTLAND',
  '38:15',
  '12:20',
  '38 of 113',
  'F 21-39',
  '21 of 53',
  '0:26',
  '38:41'],
 ['90',
  '1073',
  'RAÚL ROMERO',
  'M',
  '42',
  'PORTLAND',
  '38:23',
  '12:23',
  '52 of 78',
  'M 40-54',
  '19 of 27',
  '0:00',
  '38:23'],
 ['91',
  '1134',
  'AMANDA MATLIN',
  'F',
  '36',
  'PORTLAND',
  '39:17',
  '12:40',
  '39 of 113',
  'F 21-39',
  '22 of 53',
  '0:35',
  '39:52'],
 ['92',
  '1096',
  'SHAYLA VELASQUEZ',
  'F',
  '28',
  'TROUTDALEUTDALE',
  '39:18',
  '12:40',
  '40 of 113',
  'F 21-39',
  '23 of 53',
  '0:26',
  '39:44'],
 ['93',
  '1195',
  'PEYTON VELASQUEZ',
  'M',
  '9',
  'TROUTDALEUTDALE',
  '39:18',
  '12:40',
  '53 of 78',
  'M 20 and Under',
  '2 of 7',
  '0:26',
  '39:44'],
 ['94',
  '1176',
  'JOSHUA BRUNO',
  'M',
  '40',
  'PORTLAND',
  '39:20',
  '12:41',
  '54 of 78',
  'M 40-54',
  '20 of 27',
  '0:33',
  '39:53'],
 ['95',
  '1064',
  'DANIALE LYNCH',
  'F',
  '39',
  'PORTLAND',
  '39:28',
  '12:44',
  '41 of 113',
  'F 21-39',
  '24 of 53',
  '0:22',
  '39:50'],
 ['96',
  '1189',
  'SHAYLA TURNER',
  'F',
  '33',
  'PORTLAND',
  '39:30',
  '12:44',
  '42 of 113',
  'F 21-39',
  '25 of 53',
  '0:18',
  '39:48'],
 ['97',
  '1177',
  'MELITA LYNCH',
  'F',
  '22',
  'PORTLAND',
  '39:55',
  '12:52',
  '43 of 113',
  'F 21-39',
  '26 of 53',
  '0:23',
  '40:18'],
 ['98',
  '1178',
  'DEVON WONG',
  'M',
  '26',
  'PORTLAND',
  '39:55',
  '12:52',
  '55 of 78',
  'M 21-39',
  '25 of 33',
  '0:23',
  '40:18'],
 ['99',
  '1184',
  'KELLY BUCHANAN',
  'F',
  '28',
  'PORTLAND',
  '40:03',
  '12:55',
  '44 of 113',
  'F 21-39',
  '27 of 53',
  '0:36',
  '40:39'],
 ['100',
  '1029',
  'MOLLI MITCHELL',
  'F',
  '36',
  'PORTLAND',
  '40:21',
  '13:01',
  '45 of 113',
  'F 21-39',
  '28 of 53',
  '0:30',
  '40:51'],
 ['101',
  '1158',
  'JAYMES LATIMER',
  'M',
  '27',
  'PORTLAND',
  '40:50',
  '13:10',
  '56 of 78',
  'M 21-39',
  '26 of 33',
  '0:19',
  '41:09'],
 ['102',
  '1296',
  'SUE ANN HIGGENS',
  'F',
  '57',
  'PORTLAND',
  '41:15',
  '13:18',
  '46 of 113',
  'F 55+',
  '4 of 14',
  '0:17',
  '41:32'],
 ['103',
  '1020',
  'NAT KIM',
  'F',
  '38',
  'PORTLAND',
  '41:21',
  '13:20',
  '47 of 113',
  'F 21-39',
  '29 of 53',
  '0:10',
  '41:31'],
 ['104',
  '1052',
  'BETH BOGDEWIECZ',
  'F',
  '37',
  'PORTLAND',
  '41:50',
  '13:29',
  '48 of 113',
  'F 21-39',
  '30 of 53',
  '0:27',
  '42:17'],
 ['105',
  '1051',
  'AMBER BOGDEWIECZ',
  'F',
  '38',
  'PORTLAND',
  '41:50',
  '13:29',
  '49 of 113',
  'F 21-39',
  '31 of 53',
  '0:27',
  '42:17'],
 ['106',
  '1069',
  'PAM CROW',
  'F',
  '61',
  'PORTLAND',
  '42:04',
  '13:34',
  '50 of 113',
  'F 55+',
  '5 of 14',
  '0:23',
  '42:27'],
 ['107',
  '1076',
  'MARLON BROUSSARD',
  'M',
  '47',
  'PORTLAND',
  '42:21',
  '13:39',
  '57 of 78',
  'M 40-54',
  '21 of 27',
  '0:19',
  '42:40'],
 ['108',
  '1070',
  'HAILEI ABERSON',
  'F',
  '23',
  'PORTLAND',
  '43:01',
  '13:52',
  '51 of 113',
  'F 21-39',
  '32 of 53',
  '0:24',
  '43:25'],
 ['109',
  '1166',
  'GRACE MCBARRON',
  'F',
  '23',
  'PORTLAND',
  '43:01',
  '13:52',
  '52 of 113',
  'F 21-39',
  '33 of 53',
  '0:25',
  '43:26'],
 ['110',
  '1164',
  'AMIYAH HOLFORD',
  'F',
  '15',
  'PORTLAND',
  '43:07',
  '13:54',
  '53 of 113',
  'F 20 and Under',
  '2 of 6',
  '0:25',
  '43:32'],
 ['111',
  '1222',
  'KENNETH MARSHALL',
  'M',
  '26',
  'VANCOUVER',
  '43:20',
  '13:58',
  '58 of 78',
  'M 21-39',
  '27 of 33',
  '0:11',
  '43:31'],
 ['112',
  '1097',
  'VERNA MARSHALL',
  'F',
  '64',
  'CAMAS',
  '43:20',
  '13:59',
  '54 of 113',
  'F 55+',
  '6 of 14',
  '0:12',
  '43:32'],
 ['113',
  '1101',
  'ERIN SCHWARZ',
  'F',
  '29',
  'PORTLAND',
  '43:50',
  '14:08',
  '55 of 113',
  'F 21-39',
  '34 of 53',
  '0:37',
  '44:27'],
 ['114',
  '1144',
  'KIMBERLEY JACKSON',
  'F',
  '51',
  'PORTLAND',
  '44:46',
  '14:26',
  '56 of 113',
  'F 40-54',
  '13 of 37',
  '0:32',
  '45:18'],
 ['115',
  '1007',
  'KYLE NEWELL',
  'M',
  '57',
  'PORTLAND',
  '44:58',
  '14:30',
  '59 of 78',
  'M 55+',
  '3 of 5',
  '0:31',
  '45:29'],
 ['116',
  '1229',
  'KAREN FOSTER',
  'F',
  '39',
  'PORTLAND',
  '45:06',
  '14:32',
  '57 of 113',
  'F 21-39',
  '35 of 53',
  '0:13',
  '45:19'],
 ['117',
  '1005',
  'DELIA GRENVILLE',
  'F',
  '52',
  'PORTLAND',
  '45:10',
  '14:34',
  '58 of 113',
  'F 40-54',
  '14 of 37',
  '0:15',
  '45:25'],
 ['118',
  '1295',
  'THOMAS RUKS',
  'M',
  '50',
  'PORTLAND',
  '45:15',
  '14:36',
  '60 of 78',
  'M 40-54',
  '22 of 27',
  '0:37',
  '45:52'],
 ['119',
  '1054',
  'TRACY BOWLES',
  'F',
  '38',
  'PORTLAND',
  '46:17',
  '14:55',
  '59 of 113',
  'F 21-39',
  '36 of 53',
  '0:23',
  '46:40'],
 ['120',
  '1262',
  'KARI SCHLINKMEIER',
  'F',
  '47:28',
  '15:18',
  '60 of 113',
  '8 of 9',
  '0:13',
  '47:41'],
 ['121',
  '1024',
  'CINZIA CORIO-HOLMAN',
  'F',
  '52',
  'PORTLAND',
  '47:41',
  '15:22',
  '61 of 113',
  'F 40-54',
  '15 of 37',
  '0:23',
  '48:04'],
 ['122',
  '1088',
  'GALEN HARDEN',
  'M',
  '52',
  'PORTLAND',
  '47:56',
  '15:27',
  '61 of 78',
  'M 40-54',
  '23 of 27',
  '0:17',
  '48:13'],
 ['123',
  '1059',
  'AMIYAH BERRY',
  'F',
  '9',
  'PORTLAND',
  '48:00',
  '15:29',
  '62 of 113',
  'F 20 and Under',
  '3 of 6',
  '0:31',
  '48:31'],
 ['124',
  '1014',
  'DESIREE VIELMETTI',
  'F',
  '34',
  'PORTLAND',
  '48:02',
  '15:29',
  '63 of 113',
  'F 21-39',
  '37 of 53',
  '0:29',
  '48:31'],
 ['125',
  '1015',
  'BRITTANY BERRY HILL',
  'F',
  '29',
  'PORTLAND',
  '48:03',
  '15:30',
  '64 of 113',
  'F 21-39',
  '38 of 53',
  '0:31',
  '48:34'],
 ['126',
  '1035',
  'JESSE CHRISTENSON',
  'M',
  '37',
  'PORTLAND',
  '48:07',
  '15:31',
  '62 of 78',
  'M 21-39',
  '28 of 33',
  '0:30',
  '48:37'],
 ['127',
  '1172',
  'LOUISE MOROZ',
  'F',
  '48',
  'PEORIA',
  '48:26',
  '15:37',
  '65 of 113',
  'F 40-54',
  '16 of 37',
  '0:44',
  '49:10'],
 ['128',
  '1012',
  'MEREDITH BOWIE',
  'F',
  '37',
  'SHERWOOD',
  '48:28',
  '15:38',
  '66 of 113',
  'F 21-39',
  '39 of 53',
  '0:43',
  '49:11'],
 ['129',
  '1248',
  'TERI UNTALAN',
  'F',
  '51',
  'PORTLAND',
  '49:20',
  '15:54',
  '67 of 113',
  'F 40-54',
  '17 of 37',
  '0:27',
  '49:47'],
 ['130',
  '1249',
  'SAM MCKINSTRY',
  'M',
  '33',
  'PORTLAND',
  '49:20',
  '15:54',
  '63 of 78',
  'M 21-39',
  '29 of 33',
  '0:26',
  '49:46'],
 ['131',
  '1131',
  'MARGARET PETERSEN',
  'F',
  '13',
  'VANCOUVER',
  '51:20',
  '16:33',
  '68 of 113',
  'F 20 and Under',
  '4 of 6',
  '0:36',
  '51:56'],
 ['132',
  '1188',
  'BARBARA WOODFORD',
  'F',
  '65',
  'PORTLAND',
  '51:21',
  '16:33',
  '69 of 113',
  'F 55+',
  '7 of 14',
  '0:39',
  '52:00'],
 ['133',
  '1130',
  'DAVID PETERSEN',
  'M',
  '43',
  'VANCOUVER',
  '51:21',
  '16:34',
  '64 of 78',
  'M 40-54',
  '24 of 27',
  '0:36',
  '51:57'],
 ['134',
  '1187',
  'TOM KELLY',
  'M',
  '67',
  'PORTLAND',
  '51:24',
  '16:35',
  '65 of 78',
  'M 55+',
  '4 of 5',
  '0:38',
  '52:02'],
 ['135',

In [11]:
df = pd.DataFrame(data, columns=headers)
df

,Place,Bib,Name,Gender,Age,City,Chip Time,Chip Pace,Gender Place,Age Group,Age Group Place,Time to Start,Gun Time
0,1,1191,MAX RANDOLPH,M,29,WASHINGTON,16:48,5:25,1 of 78,M 21-39,1 of 33,0:08,16:56
1,2,1080,NEED NAME KAISER RUNNER,M,25,PORTLAND,17:31,5:39,2 of 78,M 21-39,2 of 33,0:09,17:40
2,3,1275,DAN FRANEK,M,52,PORTLAND,18:15,5:53,3 of 78,M 40-54,1 of 27,0:07,18:22
3,4,1223,PAUL TAYLOR,M,54,PORTLAND,18:31,5:58,4 of 78,M 40-54,2 of 27,0:07,18:38
4,5,1245,THEO KINMAN,M,22,19:31,6:17,5 of 78,M 21-39,3 of 33,0:09,19:40,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,187,1254,CYNTHIA HARRIS,F,64,PORTLAND,1:07:51,21:53,110 of 113,F 55+,14 of 14,1:19,1:09:10
187,188,1085,EBONY LAWRENCE,F,30,PORTLAND,1:08:12,22:00,111 of 113,F 21-39,53 of 53,0:58,1:09:10
188,189,1170,ANTHONY WILLIAMS,M,39,PORTLAND,1:09:11,22:19,78 of 78,M 21-39,33 of 33,0:08,1:09:19
189,190,2087,LEESHA POSEY,F,43,PORTLAND,1:33:53,30:17,112 of 113,F 40-54,36 of 37,0:00,1:33:53
190,191,1216,ZULMA OCHOA,F,40,GRESHAM,1:43:27,33:22,113 of 113,F 40-54,37 of 37,0:00,1:43:27

## From iplt20.com

In [13]:
url_bat = r'https://www.iplt20.com/stats/2021'
html_bat = urlopen(url_bat)
soup_bat = bs(html_bat)

In [14]:
soup_bat.title

In [15]:
headers_bat = []
for head in soup_bat.find_all('th')[:-7] :
    headers_bat.append(head.text)
headers_bat

['POS',
 'Player',
 'Mat',
 'Inns',
 'NO',
 'Runs',
 'HS',
 'Avg',
 'BF',
 'SR',
 '100',
 '50',
 '4s',
 '6s']

In [16]:

data_bat = []

for c in range(len(soup_bat.find_all('tr'))) :
    if c==0 or c>=len(soup_bat.find_all('tr'))-7 : continue
    row = soup_bat.find_all('tr')[c].find_all('td')
    l = []
    for x in row :
        l.append(x.text.strip())
    data_bat.append(l)

In [17]:
batting_data = pd.DataFrame(data_bat, columns=headers_bat)
batting_data

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
0,1,Ruturaj Gaikwad,16,16,2,635,101,45.35,466,136.26,1,4,64,23
1,2,Faf du Plessis,16,16,2,633,95,45.21,458,138.20,0,6,60,23
2,3,KL Rahul,13,13,3,626,98,62.60,451,138.80,0,6,48,30
3,4,Shikhar Dhawan,16,16,1,587,92,39.13,471,124.62,0,3,63,16
4,5,Glenn Maxwell,15,14,2,513,78,42.75,356,144.10,0,6,48,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,145,Kuldip Yadav,1,1,1,0,0,0.00,4,0.00,0,0,0,0
145,146,Sarfaraz Khan,2,2,0,0,0,0.00,4,0.00,0,0,0,0
146,147,Anuj Rawat,2,1,0,0,0,0.00,1,0.00,0,0,0,0
147,148,Jimmy Neesham,3,2,0,0,0,0.00,2,0.00,0,0,0,0
148,149,Piyush Chawla,1,1,0,0,0,0.00,2,0.00,0,0,0,0

In [18]:
batting_data.isna().sum()

POS       0
Player    0
Mat       0
Inns      0
NO        0
Runs      0
HS        0
Avg       0
BF        0
SR        0
100       0
50        0
4s        0
6s        0
dtype: int64

In [19]:
url_bowl = r'https://www.iplt20.com/stats/2021/mostWkts?stats_type=bowling'
html_bowl = urlopen(url_bowl)
soup_bowl = bs(html_bowl)

In [20]:
headers_bowl = []
for head in soup_bowl.find_all('th')[2:-5] :
    headers_bowl.append(head.text)
headers_bowl

['POS',
 'Player',
 'Mat',
 'Inns',
 'Ov',
 'Runs',
 'Wkts',
 'BBI',
 'Avg',
 'Econ',
 'SR',
 '4w',
 '5w']

In [21]:

data_bowl = []

for c in range(len(soup_bowl.find_all('tr'))) :
    if c<3 or c>=len(soup_bowl.find_all('tr'))-5: continue
    row = soup_bowl.find_all('tr')[c].find_all('td')
    l = []
    for x in row :
        l.append(x.text.strip())
    data_bowl.append(l)

In [22]:
headers_bowl

['POS',
 'Player',
 'Mat',
 'Inns',
 'Ov',
 'Runs',
 'Wkts',
 'BBI',
 'Avg',
 'Econ',
 'SR',
 '4w',
 '5w']

In [23]:
bowling_data = pd.DataFrame(data_bowl, columns=headers_bowl)
bowling_data

,POS,Player,Mat,Inns,Ov,Runs,Wkts,BBI,Avg,Econ,SR,4w,5w
0,1,Harshal Patel,15,15,56.2,459,32,5/27,14.34,8.14,10.56,1,1
1,2,Avesh Khan,16,16,61,450,24,3/13,18.75,7.37,15.25,0,0
2,3,Jasprit Bumrah,14,14,55,410,21,3/36,19.52,7.45,15.71,0,0
3,4,Shardul Thakur,16,16,59.5,527,21,3/28,25.09,8.80,17.09,0,0
4,5,Mohammad Shami,14,14,52.4,395,19,3/21,20.78,7.50,16.63,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,106,Ben Stokes,1,1,1,12,0,0/12,0.00,12.00,0.00,0,0
106,107,Dhawal Kulkarni,1,1,4,48,0,0/48,0.00,12.00,0.00,0,0
107,108,Shreyas Gopal,3,3,7,84,0,0/9,0.00,12.00,0.00,0,0
108,109,Kamlesh Nagarkoti,1,1,2,25,0,0/25,0.00,12.50,0.00,0,0
109,110,Navdeep Saini,2,2,4,52,0,0/25,0.00,13.00,0.00,0,0

In [24]:
bowling_data.isna().sum()

POS       0
Player    0
Mat       0
Inns      0
Ov        0
Runs      0
Wkts      0
BBI       0
Avg       0
Econ      0
SR        0
4w        0
5w        0
dtype: int64